Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/RegexpLiteral:
  EnforcedStyle: slashes

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/LineLength:
  Max: 120

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable